#!/usr/bin/python3
"""

I have named this script "emp" because the school I work at is named,
"Empowerment Academy." This gives me the shell features that are available
through my teacher_helper module. You can find it at
jdevries3133/teacher_helper, but it's currently quite a mess; poorly documented
and not trivial to setup.

However, once setup, you get the following usage:

Supported commands:

student [name]
    Prints the student according to Student.__str__(). Provides basic
    student and guardian information.

parent [parent/guardian name]
    Prints the student just like in student search, but search by
    parent instead of by student. Search algorithm prioritizes primary
    contacts; so a fuzzy string match with a primary contact at a
    lower confidence will be returned over a better match against a
    secondary contact.

report [student name]
    Print a report for the student that includes zoom attendance
    record.

clock
    Automatically clocks in or out of Paychex, depending on time of day
    and previous clock state.

timer [minutes] [message]
    Start a timer that will say [message] after [minutes]. The message
    will be spoken by a robot voice.

[no arguments]
    Run this script with no arguments, and it will enter the shell mode.
    Here, the helper object is instantiated in the local namespace with
    the variable name "helper". All attributes and methods are accessible.
"""

# TODO: use pathlib for portability

PATH_TO_TEACHER_HELPER_REPO_ON_YOUR_MACHINE = (
    '/Users/JohnDeVries/repos/teacher_helper'
)

import sys
locations = [
    # src
    PATH_TO_TEACHER_HELPER_REPO_ON_YOUR_MACHINE,
    # virtual environment
    (
        PATH_TO_TEACHER_HELPER_REPO_ON_YOUR_MACHINE
        + '/venv/lib/python3.8/site-packages'
    )
]
sys.path += locations

# check python version
if not (sys.version_info.major == 3 and sys.version_info.minor == 8):
    raise Exception("teacher_helper module requires python version 3.8.")

try:
    from shell import ShellUtils
except ImportError:
    raise Exception(
        'Failed to import ShellUtils from the teacher_helper module. Did you'
        'clone the teacher_helper module at jdevries3133/teacher_helper, and '
        'did you change the constant on line 30 of {} to '.format(__file__)
        + 'that repository?'
    )


if __name__ == '__main__':
    ShellUtils(sys.argv).route()
