#!/usr/bin/env python3


"""A tool for making symlinks, where you commonly want to move a real
file to a new destination, then symlink it back to its original location."""

import argparse
import os
from pathlib import Path


def flipflop(src: os.PathLike, dst: os.PathLike):
    """Move *src* to *dst*, then create a symbolic link from *dst* back to
    *src*."""
    os.rename(src, dst)
    os.symlink(dst, src)


def main(): ...

if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('source', type=Path)
    p.add_argument('destination', type=Path)
    main()

