#!/usr/bin/env python3

"""This is just a fun thing to help fourth graders practice their
multiplication tables while also showing them a neat program. I
used this while doing academic support work during the pandemic."""

import random

def random_math_fact():
    n1 = random.randint(2, 9)
    n2 = random.randint(2, 9)
    return f'Your math fact is {n1} * {n2}'

while True:
    input('Press enter to get your next math fact!')
    print(random_math_fact())
