#!/usr/bin/env python3

"""Use python's textwrap to wrap a file to 80 character columns."""

import argparse
from os import PathLike
import pathlib
import textwrap

def wrap_file(path: PathLike, line_length: int):
    with open(path, 'r') as f:
        lines = [
            textwrap.fill(l, line_length) for l in f.read().split('\n')
        ]
    with open(path, 'w') as f:
        f.write('\n'.join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('file', type=pathlib.Path)
    parser.add_argument(
        '-l', '--line-len',
        default=80,
        help='Wrap to this line length',
        type=int
    )
    args = parser.parse_args()
    wrap_file(args.file, args.line_len)


if __name__ == '__main__':
    main()
