#!/usr/bin/env python3
"""
Excel to csv. Convert the first sheet of an excel spreadsheet to a CSV file.
"""

import argparse
import csv
import sys
from pathlib import Path
from typing import Union, List

try:
    import openpyxl  # type: ignore
except ImportError:
    print('Error: openpyxl dependency missing or absent from python path. '
          'Please run "pip install openpyxl"')
    sys.exit(1)

def _parse_args():
    parser = argparse.ArgumentParser(description="Convert excel spreadsheet to csv")
    parser.add_argument('source', type=Path, nargs='+')
    return parser.parse_args()

def excel_to_csv(source: Union[Path, List[Path]]) -> None:
    if isinstance(source, list):
        [excel_to_csv(i) for i in source]
        return
    wb = openpyxl.load_workbook(source)
    sheet = wb.active
    with open(Path(source.parent, source.stem + '.csv'), 'w') as output:
        csvwriter = csv.writer(output)
        for row in sheet.rows:
            csvwriter.writerow([cell.value for cell in row])

if __name__ == '__main__':
    args = _parse_args()
    excel_to_csv(args.source)
