#!/usr/bin/python3
"""
Excel to csv. Convert the first sheet of an excel spreadsheet to a CSV file.
"""

import argparse
import csv
from io import TextIOWrapper
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print(
        'Error: openpyxl dependency missing or absent from python path. '
        'Please run "pip install openpyxl"'
    )

def _parse_args():
    parser = argparse.ArgumentParser(
        description="Convert excel spreadsheet to csv"
    )
    parser.add_argument(
        'source',
        type=Path,
    )
    parser.add_argument(
        '-o',
        '--output',
        type=argparse.FileType('w',)
    )
    return parser.parse_args()

def excel_to_csv(source: Path, output:TextIOWrapper=None) -> TextIOWrapper:
    """
    Return output buffer to the caller for closure or further modification.
    """
    wb = openpyxl.load_workbook(source)
    sheet = wb.active
    if not output:
        output = open(Path(source.parent, source.stem + '.csv'), 'w')
    csvwriter = csv.writer(output)
    for row in sheet.rows:
        csvwriter.writerow([cell.value for cell in row])
    return output

if __name__ == '__main__':
    args = _parse_args()
    i = args.source
    excel_to_csv(
        args.source,
        args.output
    ).close()
